### ISSUE TITLE
Github webpage URL needs updating to .io

### ISSUE THREAD

**Issue by dietervandoren** [sensorium/Mozzi#127]
This doesn't work anymore in About (and likely many other places): https://sensorium.github.com/mozzi/ 
But this does:  https://sensorium.github.io/mozzi/ 

Greetings, Dieter

**Comment by MrKOSMOS** [comment]
+1 on this. I saw it as well

**Comment by tfry-git** [comment]
Fixed by @sensorium in https://github.com/sensorium/Mozzi/commit/9f8d96a33c09fea1073f489d8427a9e752c174ae
