### ISSUE TITLE
Add note to installation instructions not to use Releases versions

### ISSUE THREAD

**Issue by diyelectromusic** [sensorium/Mozzi#154]
I've just been debugging compilation problems with someone trying to use some of my code using Mozzi and it turns out that they had (quite naturally) assumed they should download the latest Release not the latest "live" code.

Would it be possible to add a note in the installation section that the files in the Releases area are now legacy and that users should use the "code" button to download a ZIP file for importing into Arduino?

I must say, I thought I'd seen a note to that effect somewhere myself, but I can't find it now (so apologies if I've just missed it), but the installation section seems the logical place for a reminder.

Many thanks!
Kevin

**Comment by sensorium** [comment]
Thanks Kevin, I'll do it.
