### ISSUE TITLE
AMsynth examples do not compile under Linux due to wrong header names

### ISSUE THREAD

**Issue by kopfkopfkopfaffe** [sensorium/Mozzi#17]
**Problem**

The examples
`/examples/06.Synthesis/AMsynth`
and
`/examples/06.Synthesis//AMsynth_HIFI`

contain basically the same bug. In line 48 respectively 23, the include
`#include <tables/COS2048_int8.h>`
is written in capital letters. The actual file name however is `cos2048_int8.h`. This leads to a file not found error while compiling under linux and probably also OSX since both systems are case-sensitive in contrast to Windows.

**My system**

Ubuntu 12.4, 64-Bit. 
Arduino 1.0.5

**Comment by tfry-git** [comment]
This issue has been fixed a long time ago with https://github.com/sensorium/Mozzi/commit/0dddc1c75e62fb3cefc4f3702a1be855ff79a5ec .
