### ISSUE TITLE
URL to webpage in _About_ section is wrong

### ISSUE THREAD

**Issue by dennisppaul** [sensorium/Mozzi#252]
the URL in the _About_ section on the main page of the github repository at https://github.com/sensorium/Mozzi is wrong. it should read:

```
https://sensorium.github.io/Mozzi/
```

but instead it is:

```
https://sensorium.github.com/Mozzi/
```

**Comment by tfry-git** [comment]
@sensorium : I think that's something only you as project owner can fix. (In case you are wondering, as I was: Submitter is not referring to anything in code, README, or pages, but the github project info itself.)

**Comment by sensorium** [comment]
Thanks all.
