### ISSUE TITLE
How do you do filter envelopes?

### ISSUE THREAD

**Issue by justinjools22** [sensorium/Mozzi#265]
The envelope examples are amplitude envelopes, so how do you use envelopes with filters. I am building a design with both amplitude and filter envelopes.

**Comment by tomcombriat** [comment]
A quick answer, can elaborate more of needed.

The envelopes just return numbers. You can use these numbers to adjust the filter parameters, something like (pseudo code)
` lpf.setCutoff(envelope.next());`

**Comment by justinjools22** [comment]
Ah I see. Perfect. So you use  lpf.setCutoff(envelope.next()); then the separate ADSR values are sent to calculate the waveform. Thanks :)

**Comment by tomcombriat** [comment]
Great! Actually an example on that would be great! PR welcome ;)

Can I close this as solved?
