### ISSUE TITLE
Mozzi ignores selected reference voltage set by analogReference()/overwrites REFS0 in ADMUX when using mozziAnalogRead()

### ISSUE THREAD

**Issue by johmd** [sensorium/Mozzi#27]
mozziAnalogRead() is currently limited to "AV CC with external capacitor at AREF pin" (REFS[1:0] = 00) as the ADC reference voltage. Setting a reference via Arduino's analogReference() is ignored. Setting REFS[1:0] in ADMUX manually is also overwritten in adcSetChannel() https://github.com/sensorium/Mozzi/blob/83a929df5758bbd53d6e81566276c1c61062a027/mozzi_analog.cpp#L138.

There should be at least a warning about this unexpected behavior, since sources connected to AREF could get damaged by getting their output connected to AVCC inside the MCU when calling mozziAnalogRead().

**Comment by sensorium** [comment]
Thanks johmd, fixed in git.
