### ISSUE TITLE
library properties version line 8 crashes Arduino IDE

### ISSUE THREAD

**Issue by brunoxyz** [sensorium/Mozzi#55]
I'm getting started using mozzi but as soon as I add the library manually or via zip it crashes everything. 
By elimination it led me to line 8 (version info) of the library properties. Not sure what's wrong with it but after deleting it it loads Arduino IDE.  

I'm using windows 10

this is the line I deleted "version=version 2013-07-07-17:51 "

**Comment by sensorium** [comment]
Thanks, it's fixed in the development code. At the moment I'd recommend using the development code - it's close to release stage.
