### ISSUE TITLE
teensy 4.0 support?

### ISSUE THREAD

**Issue by CZHO404** [sensorium/Mozzi#77]
Well Teensy 4.0 is a thing and on the website for Mozzi it only lists Teensy 2.0 and 3.0. I'm a little confused if it will ever get support. Also i cant just try to use the 3.0 stuff because for some reason it only has A0 to A13.

Mozzi Pins
Teensy2, 2++ | B5 (25)
Teensy3.x | A14 (analog out)
*link to pin out*
[https://www.pjrc.com/store/teensy40.html](url)

**Comment by tfry-git** [comment]
Hi!

Adding Teensy 4.0 support will *probably* not be too hard. However, this will have to be done by somebody who has the hardware to test. Such as - you.

Main files to look at for starters:
- hardware_defines.h  - you'll probably have to add some define to IS_TEENSY3() (ignoring that this macro will then be a bit of a misnomer)
- AudioConfigTeensy3_12bit.h  - as you mention, you'll have to adjust the output pin

Chances are pretty good that this will be all you need to do. If it's not, check all occurances of IS_TEENSY3() in the Mozzi code for required adjustments.

If there are any questions: Ask. Oh, and don't forget to submit a PR, when done.

**Comment by CZHO404** [comment]
Wow thank you for your time, ill try to get to that and have a nice day

**Comment by apiel** [comment]
@czho did you manage to get it work?

**Comment by czho** [comment]
Sorry, I don't have the board and I have mostly lost interest in the project

**Comment by czho** [comment]
No, sorry
