### ISSUE TITLE
"released version" from downloads page seems really old?

### ISSUE THREAD

**Issue by skybrian** [sensorium/Mozzi#78]
I downloaded the "most recent version" from https://sensorium.github.io/Mozzi/download/

I am getting this message in Arduino:

    Invalid version 'version 2013-07-07-17:51' for library in: /Users/skybrian/Documents/Arduino/libraries/Mozzi

I looks like this was fixed many years ago and the zip file there might not actually be the most recent release? libraries.properties on GitHub says 1.0.3 and looking at the GitHub releases tab, 1.0.2 seems to be the most recent stable release.

**Comment by jeremiawuzza** [comment]
Hi Brian thanks got your email
Just in case you do want to use Mozzi again the correct version field in library.properties is version=1.1.0
After I edited that I don't get the error message any more!
Cheers
Jeremy
