### ISSUE TITLE
twi_nonblock not in master branch

### ISSUE THREAD

**Issue by moriczgergo** [sensorium/Mozzi#88]
I had to download the release instead. Is there a reason for this?

**Comment by tfry-git** [comment]
Apparently it was deleted in commit 584489fc33637c15cf315ec525582a8cb2c22741 . Probably a mistake?

**Comment by sensorium** [comment]
Removed by accident.  Now replaced.  I've been experimenting with more general nonblocking Wire and twi code for use with Mozzi, but I'm not sure it would simplify things much for users.  It still requires others to understand my modifications to the Wire code which might take as long as working out their own version for use with their particular I2C hardware.

**Comment by moriczgergo** [comment]
Alright. What could be good is a fake Wire object to pass to drivers, like most Adafruit OLED drives.
