### ISSUE TITLE
Generate sin wave without need of sin function or table

### ISSUE THREAD

**Issue by nicolas-f** [sensorium/Mozzi#91]
Hi,

Were you aware of this method ?

https://dsp.stackexchange.com/questions/68528/compute-hann-window-without-cos-function

**Comment by CZHO404** [comment]
Mozzi uses pre-calculated values.

**Comment by CZHO404** [comment]
What I mean by that is the feature that you are requesting doesn't improve anything and only really makes it run slower.

**Comment by nicolas-f** [comment]
Ok, its just instead of storing large table in memory on device you would only need 3 variables. One multiplication and one addition per sample is not a lot.

https://github.com/Ifsttar/qrtone/blob/master/jqrtone/src/main/java/org/noise_planet/qrtone/IterativeTone.java
