### ISSUE TITLE
Problem installing the library

### ISSUE THREAD

**Issue by 1schammass** [sensorium/Mozzi#94]
Hello, as a newbie at Arduino, I want to build a synthesizer to get to know the micro controller. (My kids love modular synthesizers - maybe they'll learn how to program one day ...)

But: I can't install Mozzi. When using mozzi-master.zip, the Arduino IDE says: "The library "Mozzi-master" cannot be used. Library names must contain only basic letters and numbers (ASCII only and no spaces, and it cannot start with a number)".

What do I wrong? Thank you, best regards

**Comment by sensorium** [comment]
Try renaming the folder to just "Mozzi".
